import { deriveBasisStanding } from "./standing.js";
import { SURFACE_ANSWER_ASSESSMENT_VERSION, SURFACE_BASIS_VERSION, type AnswerAssessmentProjection, type AnswerObservationRead, type BasisCompositionInput, type BasisContextProjection, type BasisContribution, type BasisContributionRef, type BasisGap, type BasisOwnerDescriptor, type BasisParseResult, type BasisProjection, type BasisProjectionParseResult, type ContributionRead, type OwnerRead, type SurfaceAssessmentRead, type SurfaceAnswerAssessmentRef, type SurfacePolicyOutcome, type ThreadAnswerRef } from "./types.js";

export const BASIS_MAX_TOTAL_BYTES = 65_536;
export const BASIS_MAX_STRING_BYTES = 4_096;
export const BASIS_MAX_CONTRIBUTIONS = 64;
export const BASIS_MAX_FIELDS = 12;
export const BASIS_MAX_DEPTH = 24;
export const BASIS_MAX_NODES = 1_024;
const encoder = new TextEncoder();
const DISALLOWED_TEXT = /[\u0000-\u001f\u007f\u202a-\u202e\u2066-\u2069<>]|(?:https?:|javascript:|data:)/iu;
type R = Record<string, unknown>; type Parse<T> = { ok: true; value: T } | { ok: false; gap: BasisGap };

export function parseBasisComposition(input: unknown): BasisParseResult {
  const snapshot = safeSnapshot(input); if (!snapshot.ok) return snapshot; const v = snapshot.value;
  if (!exact(v, ["version", "answer", "assessment", "contributions"]) || v.version !== SURFACE_BASIS_VERSION) return fail("invalid-shape", "Basis composition has an invalid shape or version.");
  const answer = parseAnswerRead(v.answer); const assessment = parseAssessmentRead(v.assessment); if (!answer.ok) return answer; if (!assessment.ok) return assessment;
  if (!Array.isArray(v.contributions) || v.contributions.length > BASIS_MAX_CONTRIBUTIONS) return fail("invalid-contributions", "Contribution cardinality is invalid.");
  const contributions: ContributionRead[] = [];
  for (const item of v.contributions) { const parsed = parseContributionRead(item); if (!parsed.ok) return parsed; contributions.push(parsed.value); }
  return { ok: true, value: { version: SURFACE_BASIS_VERSION, answer: answer.value, assessment: assessment.value, contributions } };
}

export function parseBasisProjection(input: unknown): BasisProjectionParseResult {
  const snapshot = safeSnapshot(input); if (!snapshot.ok) return snapshot; const v = snapshot.value;
  if (!exact(v, ["version", "answer", "standing", "unresolvedReason", "assessment", "regions", "relationships", "gaps"]) || v.version !== SURFACE_BASIS_VERSION) return fail("invalid-projection", "Basis projection has an invalid shape.");
  const answer = parseAnswerRead(v.answer); const assessment = parseAssessmentRead(v.assessment); const regions = parseRegions(v.regions); const gaps = parseGaps(v.gaps);
  if (!answer.ok) return answer; if (!assessment.ok) return assessment; if (!regions.ok) return regions; if (!gaps.ok) return gaps;
  const relationships = parseRelationships(v.relationships, assessment.value, regions.value); if (!relationships.ok) return relationships;
  const expected = deriveBasisStanding(answer.value, assessment.value);
  if (v.standing !== expected.standing || v.unresolvedReason !== expected.reason) return fail("projection-standing-mismatch", "Projection standing must be derived from its answer and Surface assessment.");
  return { ok: true, value: { version: SURFACE_BASIS_VERSION, answer: answer.value, standing: expected.standing, unresolvedReason: expected.reason, assessment: assessment.value, regions: regions.value, relationships: relationships.value, gaps: gaps.value } };
}

export function parseThreadAnswerRef(input: unknown): Parse<ThreadAnswerRef> {
  if (!exact(input, ["authority", "schemaVersion", "kind", "standing", "threadId", "messageId"]) || input.authority !== "@kontourai/thread" || input.schemaVersion !== "1.2.0" || input.kind !== "assistant-message" || input.standing !== "observed" || !safeOpaqueId(input.threadId) || !safeOpaqueId(input.messageId)) return fail("invalid-thread-answer", "Thread answer reference is not the published Thread 1.2.0 observed shape.");
  return { ok: true, value: input as unknown as ThreadAnswerRef };
}
function parseAnswerRead(input: unknown): Parse<AnswerObservationRead> { const parsed = parseRead(input, (value) => { if (!exact(value, ["ref", "fact", "observedAt"]) || value.fact !== "answer-observed" || !safeTimestamp(value.observedAt)) return fail("invalid-answer-observation", "Answer observation is invalid."); const ref = parseThreadAnswerRef(value.ref); return ref.ok ? { ok: true, value: { ref: ref.value, fact: "answer-observed" as const, observedAt: value.observedAt } } : ref; }); if (!parsed.ok) return parsed; return parsed.value.owner.authority === "@kontourai/thread" ? parsed as Parse<AnswerObservationRead> : fail("answer-owner-spoof", "Only Thread may provide an answer observation."); }
function parseAssessmentRead(input: unknown): Parse<SurfaceAssessmentRead> { const parsed = parseRead(input, (value) => isRecord(value) ? parseAssessment(value) : fail("invalid-assessment", "Assessment is invalid.")); if (!parsed.ok) return parsed; return parsed.value.owner.authority === "@kontourai/surface" ? parsed as Parse<SurfaceAssessmentRead> : fail("assessment-owner-spoof", "Only Surface may provide an answer assessment."); }
function parseContributionRead(input: unknown): Parse<ContributionRead> { const parsed = parseRead(input, (value) => { if (!Array.isArray(value) || value.length > BASIS_MAX_CONTRIBUTIONS) return fail("invalid-contributions", "Contribution read is invalid."); const output: BasisContribution[] = []; for (const candidate of value) { const item = parseContribution(candidate); if (!item.ok) return item; output.push(item.value); } return { ok: true, value: output }; }); if (!parsed.ok) return parsed; const authority = parsed.value.owner.authority; if (!isContributionAuthority(authority)) return fail("unsupported-owner-version", "Contribution owner must be a published authority."); if (parsed.value.state === "available" && parsed.value.value.some((item) => item.ref.authority !== authority)) return fail("owner-mismatch", "Contribution owner must exactly match every contribution ref."); return { ok: true, value: parsed.value as ContributionRead }; }
function parseRead<T>(input: unknown, parseValue: (value: unknown) => Parse<T>): Parse<OwnerRead<T, string>> { if (!isRecord(input) || !Object.hasOwn(input, "state") || !Object.hasOwn(input, "owner") || !Object.hasOwn(input, "observedAt")) return fail("invalid-owner-read", "Owner read is invalid."); const owner = parseOwnerDescriptor(input.owner); if (!owner.ok) return owner; if (!safeTimestamp(input.observedAt)) return fail("invalid-owner-read", "Owner read timestamp is invalid."); const base = { owner: owner.value, observedAt: input.observedAt }; if (input.state === "available") { if (!exact(input, ["owner", "state", "observedAt", "value"])) return fail("invalid-owner-read", "Available owner read is invalid."); const value = parseValue(input.value); return value.ok ? { ok: true, value: { ...base, state: "available", value: value.value } } : value; } if (input.state === "observed-empty") { if (!exact(input, ["owner", "state", "observedAt", "value"]) || !Array.isArray(input.value) || input.value.length !== 0) return fail("invalid-owner-read", "Observed-empty owner read is invalid."); return { ok: true, value: { ...base, state: "observed-empty", value: [] } as OwnerRead<T, string> }; } if (!["not-captured", "restricted", "stale", "corrupt", "unsupported-version", "unavailable"].includes(String(input.state)) || !exact(input, ["owner", "state", "observedAt"])) return fail("invalid-owner-read", "Owner read state is invalid."); return { ok: true, value: { ...base, state: input.state } as OwnerRead<T, string> }; }
function parseOwnerDescriptor(input: unknown): Parse<BasisOwnerDescriptor> { return exact(input, ["authority"]) && safeAuthority(input.authority) ? { ok: true, value: { authority: input.authority } } : fail("invalid-owner", "Owner descriptor is invalid."); }

function parseAssessment(value: R): Parse<AnswerAssessmentProjection> { if (!exact(value, ["version", "ref", "found", "bundle", "claim", "policy", "evidence", "derivation", "gaps"]) || value.version !== SURFACE_BASIS_VERSION || typeof value.found !== "boolean") return fail("invalid-assessment", "Assessment is invalid."); const ref = parseAssessmentRef(value.ref); const bundle = parseBundle(value.bundle); const claim = parseClaim(value.claim); const policy = parsePolicy(value.policy); const evidence = parseEvidence(value.evidence); const derivation = parseDerivation(value.derivation); const gaps = parseGaps(value.gaps); if (!ref.ok) return ref; if (!bundle.ok) return bundle; if (!claim.ok) return claim; if (!policy.ok) return policy; if (!evidence.ok) return evidence; if (!derivation.ok) return derivation; if (!gaps.ok) return gaps; if (ref.value.bundleId !== bundle.value.id || (value.found && (!claim.value || ref.value.claimId !== claim.value.id)) || (!value.found && (claim.value !== null || policy.value !== null))) return fail("assessment-ref-mismatch", "Surface assessment identity does not match its content."); return { ok: true, value: { version: SURFACE_BASIS_VERSION, ref: ref.value, found: value.found, bundle: bundle.value, claim: claim.value, policy: policy.value, evidence: evidence.value, derivation: derivation.value, gaps: gaps.value } }; }
function parseAssessmentRef(v: unknown): Parse<SurfaceAnswerAssessmentRef> { return exact(v, ["authority", "schemaVersion", "kind", "bundleId", "claimId"]) && v.authority === "@kontourai/surface" && v.schemaVersion === SURFACE_ANSWER_ASSESSMENT_VERSION && v.kind === "answer-assessment" && safeIdentifier(v.bundleId) && safeIdentifier(v.claimId) ? { ok: true, value: v as unknown as SurfaceAnswerAssessmentRef } : fail("invalid-assessment-ref", "Assessment must use the exact Surface assessment contract."); }
function parseBundle(v: unknown): Parse<AnswerAssessmentProjection["bundle"]> { return exact(v, ["id", "schemaVersion", "source", "generatedAt"]) && safeIdentifier(v.id) && Number.isSafeInteger(v.schemaVersion) && safeText(v.source) && safeTimestamp(v.generatedAt) ? { ok: true, value: v as AnswerAssessmentProjection["bundle"] } : fail("invalid-assessment", "Assessment bundle is invalid."); }
function parseClaim(v: unknown): Parse<AnswerAssessmentProjection["claim"]> { if (v === null) return { ok: true, value: null }; if (!exact(v, ["id", "subject", "status", "freshness"]) || !safeIdentifier(v.id) || !safeText(v.status) || !exact(v.subject, ["subjectType", "subjectId"]) || !safeText(v.subject.subjectType) || !safeIdentifier(v.subject.subjectId)) return fail("invalid-assessment", "Assessment claim is invalid."); if (v.freshness !== null && (!exact(v.freshness, ["asOf", "expiresAt", "stale"]) || !safeTimestamp(v.freshness.asOf) || !(v.freshness.expiresAt === null || safeTimestamp(v.freshness.expiresAt)) || typeof v.freshness.stale !== "boolean")) return fail("invalid-assessment", "Assessment freshness is invalid."); return { ok: true, value: v as AnswerAssessmentProjection["claim"] }; }
function parsePolicy(v: unknown): Parse<SurfacePolicyOutcome | null> { if (v === null) return { ok: true, value: null }; if (!exact(v, ["id", "outcome", "satisfied"]) || !safeIdentifier(v.id) || !(v.outcome === "satisfied" || v.outcome === "not-satisfied") || typeof v.satisfied !== "boolean" || v.satisfied !== (v.outcome === "satisfied")) return fail("invalid-assessment", "Surface policy outcome is invalid."); return { ok: true, value: { id: v.id, outcome: v.outcome, satisfied: v.satisfied } }; }
function parseEvidence(v: unknown): Parse<AnswerAssessmentProjection["evidence"]> { if (!exact(v, ["cited", "entails", "counterevidence"])) return fail("invalid-assessment", "Assessment evidence is invalid."); const fields = [v.cited, v.entails, v.counterevidence]; if (fields.some((x) => !Array.isArray(x) || x.length > BASIS_MAX_CONTRIBUTIONS)) return fail("invalid-assessment", "Assessment evidence cardinality is invalid."); for (const field of fields as unknown[][]) for (const item of field) if (!exact(item, ["id", "label", "sourceRef", "observedAt"]) || !safeIdentifier(item.id) || !safeText(item.label) || !safeText(item.sourceRef) || !safeTimestamp(item.observedAt)) return fail("invalid-assessment", "Assessment evidence item is invalid."); return { ok: true, value: v as AnswerAssessmentProjection["evidence"] }; }
function parseDerivation(v: unknown): Parse<AnswerAssessmentProjection["derivation"]> { if (!exact(v, ["available", "directInputs"]) || typeof v.available !== "boolean" || !Array.isArray(v.directInputs) || v.directInputs.length > BASIS_MAX_CONTRIBUTIONS) return fail("invalid-assessment", "Assessment derivation is invalid."); for (const item of v.directInputs) if (!exact(item, ["claimId", "status"]) || !safeIdentifier(item.claimId) || !(item.status === null || safeText(item.status))) return fail("invalid-assessment", "Assessment derivation input is invalid."); return { ok: true, value: v as AnswerAssessmentProjection["derivation"] }; }

function parseContribution(v: unknown): Parse<BasisContribution> { if (!exact(v, ["ref", "answer", "role", "context"], ["gaps", "relationships"])) return fail("invalid-contribution", "Contribution is invalid."); const ref = parseContributionRef(v.ref); const answer = parseThreadAnswerRef(v.answer); const context = parseContext(v.context); const gaps = v.gaps === undefined ? { ok: true as const, value: [] as BasisGap[] } : parseGaps(v.gaps); if (!ref.ok) return ref; if (!answer.ok) return answer; if (!context.ok) return context; if (!gaps.ok) return gaps; if (!validContributionPlacement(ref.value, v.role, context.value.kind)) return fail("invalid-contribution-placement", "Contribution ref, role, and context must use their published combination."); const relationships = v.relationships === undefined ? { ok: true as const, value: undefined } : parseContextRelationships(v.relationships, ref.value); if (!relationships.ok) return relationships; return { ok: true, value: { ref: ref.value, answer: answer.value, role: v.role as BasisContribution["role"], context: context.value, ...(v.gaps === undefined ? {} : { gaps: gaps.value }), ...(relationships.value === undefined ? {} : { relationships: relationships.value }) } }; }
function parseContextRelationships(v: unknown, ownerRef: BasisContributionRef): Parse<BasisContribution["relationships"]> { if (!Array.isArray(v) || v.length > BASIS_MAX_FIELDS) return fail("invalid-contribution", "Contribution relationships are invalid."); const output: NonNullable<BasisContribution["relationships"]>[number][] = []; for (const item of v) { if (!exact(item, ["contract", "kind", "from", "to"], ["gaps"]) || !exact(item.contract, ["authority", "schemaVersion", "kind"]) || !safeAuthority(item.contract.authority) || !safeText(item.contract.schemaVersion) || item.contract.kind !== "basis-context-relationship" || !isContextRelationshipKind(item.kind)) return fail("invalid-contribution", "Context relationship is invalid."); const from = parseContributionRef(item.from); const to = parseContributionRef(item.to); const gaps = item.gaps === undefined ? { ok: true as const, value: [] as BasisGap[] } : parseGaps(item.gaps); if (!from.ok) return from; if (!to.ok) return to; if (!gaps.ok) return gaps; if (!sameRef(from.value, ownerRef) && !sameRef(to.value, ownerRef)) return fail("relationship-endpoint-mismatch", "A context relationship must be attached to one of its endpoints."); output.push({ contract: item.contract as NonNullable<BasisContribution["relationships"]>[number]["contract"], kind: item.kind, from: from.value, to: to.value, ...(item.gaps === undefined ? {} : { gaps: gaps.value }) }); } return { ok: true, value: output }; }
function parseContributionRef(v: unknown): Parse<BasisContributionRef> { if (!isRecord(v) || !safeAuthority(v.authority) || !safeText(v.schemaVersion) || !safeText(v.kind)) return fail("invalid-contribution-ref", "Contribution ref is invalid."); const required = v.authority === "@kontourai/thread" && v.schemaVersion === "1.2.0" && v.kind === "result" ? ["authority", "schemaVersion", "kind", "threadId", "resultId"] : v.authority === "@kontourai/station" && v.schemaVersion === "1" && v.kind === "input" ? ["authority", "schemaVersion", "kind", "sessionId", "eventId"] : v.authority === "@kontourai/station" && v.schemaVersion === "1" && v.kind === "task-output" ? ["authority", "schemaVersion", "kind", "taskId", "outputId"] : v.authority === "@kontourai/station" && v.schemaVersion === "1" && v.kind === "live" ? ["authority", "schemaVersion", "kind", "sessionId", "observationId"] : v.authority === "@kontourai/flow-agents" && v.schemaVersion === "grounded-execution-narrative/v1" && v.kind === "narrative" ? ["authority", "schemaVersion", "kind", "narrativeId"] : null; if (!required || !exact(v, required) || required.some((key) => !["authority", "schemaVersion", "kind"].includes(key) && !safeIdentifier(v[key]))) return fail("unsupported-owner-version", "Contribution requires a published exact owner contract."); return { ok: true, value: v as BasisContributionRef }; }
function parseContext(v: unknown): Parse<BasisContextProjection> { if (!isRecord(v) || !safeText(v.kind)) return fail("unsafe-context", "Context projection is invalid."); const valid = (v.kind === "station-input" && exact(v, ["kind", "inputKind", "attachmentCount"], ["promptExcerpt"]) && safeText(v.inputKind) && (v.promptExcerpt === undefined || safeText(v.promptExcerpt)) && cardinal(v.attachmentCount)) || (v.kind === "thread-result" && exact(v, ["kind", "name", "terminalStatus", "truncatedParts", "omittedParts"], ["textParts"]) && safeText(v.name) && safeText(v.terminalStatus) && (v.textParts === undefined || cardinal(v.textParts)) && cardinal(v.truncatedParts) && cardinal(v.omittedParts)) || (v.kind === "station-output" && exact(v, ["kind", "title", "mediaType", "byteLength", "digest"]) && safeText(v.title) && safeText(v.mediaType) && cardinal(v.byteLength) && safeIdentifier(v.digest)) || (v.kind === "station-live" && exact(v, ["kind", "state", "observedAt"]) && safeText(v.state) && safeTimestamp(v.observedAt)) || (v.kind === "grounded-narrative" && exact(v, ["kind", "statementCount", "sourceCompleteness"]) && cardinal(v.statementCount) && ["complete", "partial", "unknown"].includes(String(v.sourceCompleteness))); return valid ? { ok: true, value: v as BasisContextProjection } : fail("unsafe-context", "Context projection is invalid."); }

function parseRegions(v: unknown): Parse<BasisProjection["regions"]> { const names = ["inputs", "execution", "process", "outcomes", "support", "sources", "live"] as const; if (!exact(v, names)) return fail("invalid-projection", "Regions are invalid."); const output = {} as { [K in keyof BasisProjection["regions"]]: BasisProjection["regions"][K] }; for (const name of names) { const list = v[name]; if (!Array.isArray(list) || list.length > BASIS_MAX_CONTRIBUTIONS) return fail("invalid-projection", "Region cardinality is invalid."); const items: BasisProjection["regions"][typeof name][number][] = []; for (const item of list) { if (!exact(item, ["ref", "role", "context", "gaps"])) return fail("invalid-projection", "Region item is invalid."); const ref = parseContributionRef(item.ref); const context = parseContext(item.context); const gaps = parseGaps(item.gaps); if (!ref.ok) return ref; if (!context.ok) return context; if (!gaps.ok || !validContributionPlacement(ref.value, item.role, context.value.kind) || regionFor(item.role) !== name) return fail("invalid-projection-placement", "Region item is placed outside its published region."); items.push({ ref: ref.value, role: item.role as BasisContribution["role"], context: context.value, gaps: gaps.value }); } output[name] = items; } return { ok: true, value: output }; }
function parseRelationships(v: unknown, assessment: SurfaceAssessmentRead, regions: BasisProjection["regions"]): Parse<BasisProjection["relationships"]> { if (!Array.isArray(v) || v.length > BASIS_MAX_CONTRIBUTIONS) return fail("invalid-projection", "Relationships are invalid."); const refs = new Set(Object.values(regions).flatMap((items) => items.map((item) => refKey(item.ref)))); const output: BasisProjection["relationships"][number][] = []; for (const item of v) { if (!exact(item, ["kind", "from", "to", "source", "gaps"]) || typeof item.from !== "string" || typeof item.to !== "string") return fail("invalid-projection", "Relationship is invalid."); const gaps = parseGaps(item.gaps); if (!gaps.ok) return gaps; if (item.source === "surface-assessment") { if (!isSurfaceRelationshipKind(item.kind) || !validSurfaceEndpoints(item.kind, item.from, item.to, assessment)) return fail("relationship-source-mismatch", "Surface relationship has an invalid kind or endpoint."); } else if (item.source === "owner-context") { if (!isContextRelationshipKind(item.kind) || !refs.has(item.from) || !refs.has(item.to)) return fail("relationship-source-mismatch", "Owner context relationship has an invalid kind or endpoint."); } else return fail("relationship-source-mismatch", "Relationship source is invalid."); output.push({ kind: item.kind as BasisProjection["relationships"][number]["kind"], from: item.from, to: item.to, source: item.source, gaps: gaps.value }); } return { ok: true, value: output }; }
function validSurfaceEndpoints(kind: unknown, from: string, to: string, assessment: SurfaceAssessmentRead): boolean { if (assessment.state !== "available" || !assessment.value.found || !assessment.value.claim) return false; const a = assessment.value; const claim = a.claim!.id; return kind === "cites" ? from === claim && a.evidence.cited.some((x) => to === `evidence:${x.id}`) : kind === "supports" ? to === claim && a.evidence.entails.some((x) => from === `evidence:${x.id}`) : kind === "counterevidence" ? to === claim && a.evidence.counterevidence.some((x) => from === `evidence:${x.id}`) : kind === "derived-from" && from === claim && a.derivation.directInputs.some((x) => to === `claim:${x.claimId}`); }
function parseGaps(v: unknown): Parse<BasisGap[]> { if (!Array.isArray(v) || v.length > BASIS_MAX_CONTRIBUTIONS) return fail("invalid-gaps", "Gaps are invalid."); const gaps: BasisGap[] = []; for (const item of v) { if (!exact(item, ["code", "message"]) || !safeText(item.code) || !safeText(item.message)) return fail("invalid-gaps", "Gap is invalid."); gaps.push({ code: item.code, message: item.message }); } return { ok: true, value: gaps }; }
function validContributionPlacement(ref: BasisContributionRef, role: unknown, context: BasisContextProjection["kind"]): boolean { return ref.authority === "@kontourai/thread" ? ref.kind === "result" && role === "execution" && context === "thread-result" : ref.authority === "@kontourai/station" && ref.kind === "input" ? role === "input" && context === "station-input" : ref.authority === "@kontourai/station" && ref.kind === "task-output" ? role === "outcome" && context === "station-output" : ref.authority === "@kontourai/station" && ref.kind === "live" ? role === "live" && context === "station-live" : ref.authority === "@kontourai/flow-agents" && ref.kind === "narrative" && role === "execution" && context === "grounded-narrative"; }
function regionFor(role: unknown): keyof BasisProjection["regions"] | null { return role === "input" ? "inputs" : role === "execution" ? "execution" : role === "process" ? "process" : role === "outcome" ? "outcomes" : role === "source" ? "sources" : role === "live" ? "live" : null; }
function isContributionAuthority(v: string): v is BasisContributionRef["authority"] { return v === "@kontourai/thread" || v === "@kontourai/station" || v === "@kontourai/flow-agents"; }
function isContextRelationshipKind(v: unknown): v is "observed-during" | "produced" | "checked-by" | "kept-in-task" { return v === "observed-during" || v === "produced" || v === "checked-by" || v === "kept-in-task"; }
function isSurfaceRelationshipKind(v: unknown): v is "cites" | "supports" | "derived-from" | "counterevidence" { return v === "cites" || v === "supports" || v === "derived-from" || v === "counterevidence"; }
function sameRef(a: BasisContributionRef, b: BasisContributionRef): boolean { return refKey(a) === refKey(b); }
function refKey(ref: BasisContributionRef): string { return Object.keys(ref).sort().map((key) => `${key}=${(ref as Record<string, string>)[key]}`).join("\u0000"); }
function exact(value: unknown, required: readonly string[], optional: readonly string[] = []): value is R { return isRecord(value) && required.every((key) => Object.hasOwn(value, key)) && Object.keys(value).every((key) => required.includes(key) || optional.includes(key)); }
function isRecord(v: unknown): v is R { return typeof v === "object" && v !== null && !Array.isArray(v); }
function byteLength(v: string): number | null { if (v.length === 0 || v.length > BASIS_MAX_STRING_BYTES) return null; const result = encoder.encode(v).byteLength; return result <= BASIS_MAX_STRING_BYTES ? result : null; }
function safeText(v: unknown): v is string { return typeof v === "string" && byteLength(v) !== null && v === v.normalize("NFC") && !DISALLOWED_TEXT.test(v); }
function safeOpaqueId(v: unknown): v is string { return typeof v === "string" && byteLength(v) !== null; }
function safeIdentifier(v: unknown): v is string { return safeText(v); }
function safeAuthority(v: unknown): v is string { return safeText(v) && /^@kontourai\/[a-z0-9-]+$/u.test(v); }
function safeTimestamp(v: unknown): v is string { return safeText(v) && Number.isFinite(Date.parse(v)); }
function cardinal(v: unknown): v is number { return typeof v === "number" && Number.isSafeInteger(v) && v >= 0 && v <= 1_000_000_000; }
function safeSnapshot(input: unknown): Parse<R> {
  const ancestors = new WeakSet<object>(); let nodes = 0; let bytes = 0;
  const account = (text: string, overhead: number) => { const n = byteLength(text); if (n === null || (bytes += n + overhead) > BASIS_MAX_TOTAL_BYTES) throw new Error("oversize"); };
  const visit = (value: unknown, depth: number): unknown => {
    if (++nodes > BASIS_MAX_NODES || depth > BASIS_MAX_DEPTH) throw new Error("limits");
    if (value === null || typeof value === "boolean" || typeof value === "number") return value;
    if (typeof value === "string") { account(value, 2); return value; }
    if (typeof value !== "object" || ancestors.has(value)) throw new Error("hostile");
    ancestors.add(value);
    try {
      if (Array.isArray(value)) {
        const length = Object.getOwnPropertyDescriptor(value, "length");
        if (!length || !("value" in length) || !Number.isSafeInteger(length.value) || length.value > BASIS_MAX_NODES) throw new Error("array-limit");
        const keys = Reflect.ownKeys(value);
        if (keys.length !== length.value + 1 || keys.some((key) => key !== "length" && (typeof key !== "string" || !/^(0|[1-9][0-9]*)$/u.test(key) || Number(key) >= length.value))) throw new Error("array-shape");
        const output: unknown[] = [];
        for (let i = 0; i < length.value; i++) { const descriptor = Object.getOwnPropertyDescriptor(value, String(i)); if (!descriptor || !("value" in descriptor)) throw new Error("accessor"); output.push(visit(descriptor.value, depth + 1)); }
        return output;
      }
      const keys = Reflect.ownKeys(value); if (keys.length > BASIS_MAX_FIELDS) throw new Error("field-limit");
      const output: R = {};
      for (const key of keys) { if (typeof key !== "string") throw new Error("field-limit"); account(key, 3); const descriptor = Object.getOwnPropertyDescriptor(value, key); if (!descriptor || !descriptor.enumerable || !("value" in descriptor)) throw new Error("accessor"); output[key] = visit(descriptor.value, depth + 1); }
      return output;
    } finally { ancestors.delete(value); }
  };
  try { const result = visit(input, 0); return isRecord(result) ? { ok: true, value: result } : fail("invalid-shape", "Basis input must be an object."); } catch { return fail("hostile-input", "Basis input is hostile, cyclic, or exceeds a parser budget."); }
}
function fail(code: string, message: string): { ok: false; gap: BasisGap } { return { ok: false, gap: { code, message } }; }
