import { deriveBasisStanding } from "./standing.js";
import { SURFACE_ANSWER_ASSESSMENT_VERSION, SURFACE_BASIS_VERSION, SURFACE_BASIS_V2_VERSION, type AnswerAssessmentProjection, type AnswerObservationRead, type BasisCompositionInput, type BasisCompositionInputV2, type BasisContextProjection, type BasisContextProjectionV2, type BasisContribution, type BasisContributionRef, type BasisContributionRefV2, type BasisGap, type BasisOwnerDescriptor, type BasisParseResult, type BasisProjection, type BasisProjectionParseResult, type BasisProjectionV2, type BasisV2ParseResult, type BasisV2ProjectionParseResult, type ContributionRead, type ContributionReadV2, type OwnerRead, type SurfaceAssessmentRead, type SurfaceAnswerAssessmentRef, type SurfacePolicyOutcome, type ThreadAnswerRef } from "./types.js";
import { BASIS_MAX_STRING_BYTES, hasExactKeys, isBasisAuthority, isBasisInertDisplayScalar, isBasisOpaqueRefScalar, isBasisRestrictedContractScalar, isPlainRecord, parseSurfacePolicyOutcome } from "./validation.js";

export const BASIS_MAX_TOTAL_BYTES = 65_536;
export { BASIS_MAX_STRING_BYTES } from "./validation.js";
export const BASIS_MAX_CONTRIBUTIONS = 64;
export const BASIS_MAX_FIELDS = 12;
export const BASIS_MAX_DEPTH = 24;
export const BASIS_MAX_NODES = 1_024;
type R = Record<string, unknown>; type Parse<T> = { ok: true; value: T } | { ok: false; gap: BasisGap };

export function parseBasisComposition(input: unknown): BasisParseResult {
  const snapshot = safeSnapshot(input); if (!snapshot.ok) return snapshot; const v = snapshot.value;
  if (!exact(v, ["version", "answer", "assessment", "contributions"]) || v.version !== SURFACE_BASIS_VERSION) return fail("invalid-shape", "Basis composition has an invalid shape or version.");
  const answer = parseAnswerRead(v.answer); const assessment = parseAssessmentRead(v.assessment); if (!answer.ok) return answer; if (!assessment.ok) return assessment;
  if (!Array.isArray(v.contributions) || v.contributions.length > BASIS_MAX_CONTRIBUTIONS) return fail("invalid-contributions", "Contribution cardinality is invalid.");
  const contributions: ContributionRead[] = [];
  for (const item of v.contributions) { const parsed = parseContributionRead(item); if (!parsed.ok) return parsed; contributions.push(parsed.value); }
  return { ok: true, value: { version: SURFACE_BASIS_VERSION, answer: answer.value, assessment: assessment.value, contributions } };
}

export function parseBasisProjection(input: unknown): BasisProjectionParseResult {
  const snapshot = safeSnapshot(input); if (!snapshot.ok) return snapshot; const v = snapshot.value;
  if (!exact(v, ["version", "answer", "standing", "unresolvedReason", "assessment", "regions", "relationships", "gaps"]) || v.version !== SURFACE_BASIS_VERSION) return fail("invalid-projection", "Basis projection has an invalid shape.");
  const answer = parseAnswerRead(v.answer); const assessment = parseAssessmentRead(v.assessment); const regions = parseRegions(v.regions); const gaps = parseGaps(v.gaps);
  if (!answer.ok) return answer; if (!assessment.ok) return assessment; if (!regions.ok) return regions; if (!gaps.ok) return gaps;
  const relationships = parseRelationships(v.relationships, assessment.value); if (!relationships.ok) return relationships;
  const expected = deriveBasisStanding(answer.value, assessment.value);
  if (v.standing !== expected.standing || v.unresolvedReason !== expected.reason) return fail("projection-standing-mismatch", "Projection standing must be derived from its answer and Surface assessment.");
  return { ok: true, value: { version: SURFACE_BASIS_VERSION, answer: answer.value, standing: expected.standing, unresolvedReason: expected.reason, assessment: assessment.value, regions: regions.value, relationships: relationships.value, gaps: gaps.value } };
}

export function parseThreadAnswerRef(input: unknown): Parse<ThreadAnswerRef> {
  const snapshot = safeSnapshot(input);
  if (!snapshot.ok) return fail("invalid-thread-answer", "Thread answer reference is not the published Thread 1.2.0 observed shape.");
  const ref = snapshot.value;
  if (!exact(ref, ["authority", "schemaVersion", "kind", "standing", "threadId", "messageId"]) || ref.authority !== "@kontourai/thread" || ref.schemaVersion !== "1.2.0" || ref.kind !== "assistant-message" || ref.standing !== "observed" || !safeOpaqueId(ref.threadId) || !safeOpaqueId(ref.messageId)) return fail("invalid-thread-answer", "Thread answer reference is not the published Thread 1.2.0 observed shape.");
  return { ok: true, value: { authority: "@kontourai/thread", schemaVersion: "1.2.0", kind: "assistant-message", standing: "observed", threadId: ref.threadId, messageId: ref.messageId } };
}
function parseAnswerRead(input: unknown): Parse<AnswerObservationRead> { const parsed = parseRead(input, (value) => { if (!exact(value, ["ref", "fact", "observedAt"]) || value.fact !== "answer-observed" || !safeTimestamp(value.observedAt)) return fail("invalid-answer-observation", "Answer observation is invalid."); const ref = parseThreadAnswerRef(value.ref); return ref.ok ? { ok: true, value: { ref: ref.value, fact: "answer-observed" as const, observedAt: value.observedAt } } : ref; }); if (!parsed.ok) return parsed; return parsed.value.owner.authority === "@kontourai/thread" ? parsed as Parse<AnswerObservationRead> : fail("answer-owner-spoof", "Only Thread may provide an answer observation."); }
function parseAssessmentRead(input: unknown): Parse<SurfaceAssessmentRead> { const parsed = parseRead(input, (value) => isRecord(value) ? parseAssessment(value) : fail("invalid-assessment", "Assessment is invalid.")); if (!parsed.ok) return parsed; return parsed.value.owner.authority === "@kontourai/surface" ? parsed as Parse<SurfaceAssessmentRead> : fail("assessment-owner-spoof", "Only Surface may provide an answer assessment."); }
function parseContributionRead(input: unknown): Parse<ContributionRead> { const parsed = parseRead(input, (value) => { if (!Array.isArray(value) || value.length > BASIS_MAX_CONTRIBUTIONS) return fail("invalid-contributions", "Contribution read is invalid."); const output: BasisContribution[] = []; for (const candidate of value) { const item = parseContribution(candidate); if (!item.ok) return item; output.push(item.value); } return { ok: true, value: output }; }); if (!parsed.ok) return parsed; const authority = parsed.value.owner.authority; if (!isContributionAuthority(authority)) return fail("unsupported-owner-version", "Contribution owner must be a published authority."); if (parsed.value.state === "available" && parsed.value.value.some((item) => item.ref.authority !== authority)) return fail("owner-mismatch", "Contribution owner must exactly match every contribution ref."); return { ok: true, value: parsed.value as ContributionRead }; }
function parseRead<T>(input: unknown, parseValue: (value: unknown) => Parse<T>): Parse<OwnerRead<T, string>> { if (!isRecord(input) || !Object.hasOwn(input, "state") || !Object.hasOwn(input, "owner") || !Object.hasOwn(input, "observedAt")) return fail("invalid-owner-read", "Owner read is invalid."); const owner = parseOwnerDescriptor(input.owner); if (!owner.ok) return owner; if (!safeTimestamp(input.observedAt)) return fail("invalid-owner-read", "Owner read timestamp is invalid."); const base = { owner: owner.value, observedAt: input.observedAt }; if (input.state === "available") { if (!exact(input, ["owner", "state", "observedAt", "value"])) return fail("invalid-owner-read", "Available owner read is invalid."); const value = parseValue(input.value); return value.ok ? { ok: true, value: { ...base, state: "available", value: value.value } } : value; } if (input.state === "observed-empty") { if (!exact(input, ["owner", "state", "observedAt", "value"]) || !Array.isArray(input.value) || input.value.length !== 0) return fail("invalid-owner-read", "Observed-empty owner read is invalid."); return { ok: true, value: { ...base, state: "observed-empty", value: [] } as OwnerRead<T, string> }; } if (!["not-captured", "restricted", "stale", "corrupt", "unsupported-version", "unavailable"].includes(String(input.state)) || !exact(input, ["owner", "state", "observedAt"])) return fail("invalid-owner-read", "Owner read state is invalid."); return { ok: true, value: { ...base, state: input.state } as OwnerRead<T, string> }; }
function parseOwnerDescriptor(input: unknown): Parse<BasisOwnerDescriptor> { return exact(input, ["authority"]) && safeAuthority(input.authority) ? { ok: true, value: { authority: input.authority } } : fail("invalid-owner", "Owner descriptor is invalid."); }

function parseAssessment(value: R): Parse<AnswerAssessmentProjection> { if (!exact(value, ["version", "ref", "found", "bundle", "claim", "policy", "evidence", "derivation", "gaps"]) || value.version !== SURFACE_ANSWER_ASSESSMENT_VERSION || typeof value.found !== "boolean") return fail("invalid-assessment", "Assessment is invalid or uses an unsupported wire version."); const ref = parseAssessmentRef(value.ref); const bundle = parseBundle(value.bundle); const claim = parseClaim(value.claim); const policy = parsePolicy(value.policy); const evidence = parseEvidence(value.evidence); const derivation = parseDerivation(value.derivation); const gaps = parseGaps(value.gaps); if (!ref.ok) return ref; if (!bundle.ok) return bundle; if (!claim.ok) return claim; if (!policy.ok) return policy; if (!evidence.ok) return evidence; if (!derivation.ok) return derivation; if (!gaps.ok) return gaps; if (ref.value.bundleId !== bundle.value.id || (value.found && (!claim.value || ref.value.claimId !== claim.value.id)) || (!value.found && (claim.value !== null || policy.value !== null))) return fail("assessment-ref-mismatch", "Surface assessment identity does not match its content."); return { ok: true, value: { version: SURFACE_ANSWER_ASSESSMENT_VERSION, ref: ref.value, found: value.found, bundle: bundle.value, claim: claim.value, policy: policy.value, evidence: evidence.value, derivation: derivation.value, gaps: gaps.value } }; }
function parseAssessmentRef(v: unknown): Parse<SurfaceAnswerAssessmentRef> { return exact(v, ["authority", "schemaVersion", "kind", "bundleId", "claimId"]) && v.authority === "@kontourai/surface" && v.schemaVersion === SURFACE_ANSWER_ASSESSMENT_VERSION && v.kind === "answer-assessment" && safeIdentifier(v.bundleId) && safeIdentifier(v.claimId) ? { ok: true, value: v as unknown as SurfaceAnswerAssessmentRef } : fail("invalid-assessment-ref", "Assessment must use the exact Surface assessment contract."); }
function parseBundle(v: unknown): Parse<AnswerAssessmentProjection["bundle"]> { return exact(v, ["id", "schemaVersion", "source", "generatedAt"]) && safeIdentifier(v.id) && Number.isSafeInteger(v.schemaVersion) && safeDisplay(v.source) && safeTimestamp(v.generatedAt) ? { ok: true, value: v as AnswerAssessmentProjection["bundle"] } : fail("invalid-assessment", "Assessment bundle is invalid."); }
function parseClaim(v: unknown): Parse<AnswerAssessmentProjection["claim"]> { if (v === null) return { ok: true, value: null }; if (!exact(v, ["id", "subject", "status", "freshness"]) || !safeIdentifier(v.id) || !safeDisplay(v.status) || !exact(v.subject, ["subjectType", "subjectId"]) || !safeDisplay(v.subject.subjectType) || !safeIdentifier(v.subject.subjectId)) return fail("invalid-assessment", "Assessment claim is invalid."); if (v.freshness !== null && (!exact(v.freshness, ["asOf", "expiresAt", "stale"]) || !safeTimestamp(v.freshness.asOf) || !(v.freshness.expiresAt === null || safeTimestamp(v.freshness.expiresAt)) || typeof v.freshness.stale !== "boolean")) return fail("invalid-assessment", "Assessment freshness is invalid."); return { ok: true, value: v as AnswerAssessmentProjection["claim"] }; }
function parsePolicy(v: unknown): Parse<SurfacePolicyOutcome | null> { if (v === null) return { ok: true, value: null }; const policy = parseSurfacePolicyOutcome(v); return policy && safeTimestamp(policy.evaluatedAt) ? { ok: true, value: policy } : fail("invalid-assessment", "Surface policy outcome is invalid."); }
function parseEvidence(v: unknown): Parse<AnswerAssessmentProjection["evidence"]> { if (!exact(v, ["cited", "entails", "undeclared", "counterevidence"])) return fail("invalid-assessment", "Assessment evidence is invalid."); const fields: Array<[unknown, "cited" | "entails" | null | "counterevidence"]> = [[v.cited, "cited"], [v.entails, "entails"], [v.undeclared, null], [v.counterevidence, "counterevidence"]]; if (fields.some(([items]) => !Array.isArray(items) || items.length > BASIS_MAX_CONTRIBUTIONS)) return fail("invalid-assessment", "Assessment evidence cardinality is invalid."); for (const [field, declaredStrength] of fields) for (const item of field as unknown[]) { if (!isRecord(item)) return fail("invalid-assessment", "Assessment evidence item is invalid."); const validStrength = declaredStrength === "counterevidence" ? item.supportStrength === "entails" || item.supportStrength === null : item.supportStrength === declaredStrength; if (!exact(item, ["id", "label", "sourceRef", "locator", "observedAt", "supportStrength", "result", "blocksClaim"]) || !safeIdentifier(item.id) || !safeDisplay(item.label) || !safeOpaqueId(item.sourceRef) || !(item.locator === null || safeOpaqueId(item.locator)) || !safeTimestamp(item.observedAt) || !validStrength || !["passed", "failed", "not-evaluated"].includes(String(item.result)) || typeof item.blocksClaim !== "boolean") return fail("invalid-assessment", "Assessment evidence item is invalid."); if (declaredStrength === "counterevidence" && !(item.result === "failed" && item.blocksClaim === true)) return fail("invalid-assessment", "Counterevidence must be failed and blocking."); } return { ok: true, value: v as AnswerAssessmentProjection["evidence"] }; }
function parseDerivation(v: unknown): Parse<AnswerAssessmentProjection["derivation"]> { if (!exact(v, ["available", "directInputs"]) || typeof v.available !== "boolean" || !Array.isArray(v.directInputs) || v.directInputs.length > BASIS_MAX_CONTRIBUTIONS) return fail("invalid-assessment", "Assessment derivation is invalid."); for (const item of v.directInputs) { if (!exact(item, ["claimId", "status", "source", "edge"]) || !safeIdentifier(item.claimId) || !(item.status === null || safeDisplay(item.status)) || !(item.source === "derivedFrom" || item.source === "derivationEdges") || !parseDerivationEdge(item.edge)) return fail("invalid-assessment", "Assessment derivation input is invalid."); if ((item.source === "derivedFrom") !== (item.edge === null)) return fail("invalid-assessment", "Assessment derivation source and edge must agree."); } return { ok: true, value: v as AnswerAssessmentProjection["derivation"] }; }
function parseDerivationEdge(v: unknown): boolean { return v === null || (exact(v, ["method", "supportStrength", "rationale"]) && (v.method === null || ["sum", "max", "min", "model", "rule-application", "copy", "normalization", "manual"].includes(String(v.method))) && (v.supportStrength === null || ["weak", "moderate", "strong"].includes(String(v.supportStrength))) && (v.rationale === null || safeDisplay(v.rationale))); }

function parseContribution(v: unknown): Parse<BasisContribution> { if (!exact(v, ["ref", "answer", "role", "context"], ["gaps"])) return fail("invalid-contribution", "Contribution is invalid."); const ref = parseContributionRef(v.ref); const answer = parseThreadAnswerRef(v.answer); const context = parseContext(v.context); const gaps = v.gaps === undefined ? { ok: true as const, value: [] as BasisGap[] } : parseGaps(v.gaps); if (!ref.ok) return ref; if (!answer.ok) return answer; if (!context.ok) return context; if (!gaps.ok) return gaps; if (!validContributionPlacement(ref.value, v.role, context.value.kind)) return fail("invalid-contribution-placement", "Contribution ref, role, and context must use their published combination."); return { ok: true, value: { ref: ref.value, answer: answer.value, role: v.role as BasisContribution["role"], context: context.value, ...(v.gaps === undefined ? {} : { gaps: gaps.value }) } }; }
function parseContributionRef(v: unknown): Parse<BasisContributionRef> { if (!isRecord(v) || !safeAuthority(v.authority) || !safeRestricted(v.schemaVersion) || !safeRestricted(v.kind)) return fail("invalid-contribution-ref", "Contribution ref is invalid."); const required = v.authority === "@kontourai/thread" && v.schemaVersion === "1.2.0" && v.kind === "result" ? ["authority", "schemaVersion", "kind", "threadId", "resultId"] : v.authority === "@kontourai/station" && v.schemaVersion === "1" && v.kind === "input" ? ["authority", "schemaVersion", "kind", "sessionId", "eventId"] : v.authority === "@kontourai/station" && v.schemaVersion === "1" && v.kind === "task-output" ? ["authority", "schemaVersion", "kind", "taskId", "outputId"] : v.authority === "@kontourai/station" && v.schemaVersion === "1" && v.kind === "live" ? ["authority", "schemaVersion", "kind", "sessionId", "observationId"] : v.authority === "@kontourai/flow-agents" && v.schemaVersion === "grounded-execution-narrative/v1" && v.kind === "narrative" ? ["authority", "schemaVersion", "kind", "narrativeId"] : null; if (!required || !exact(v, required) || required.some((key) => !["authority", "schemaVersion", "kind"].includes(key) && !safeIdentifier(v[key]))) return fail("unsupported-owner-version", "Contribution requires a published exact owner contract."); return { ok: true, value: v as BasisContributionRef }; }
function parseContext(v: unknown): Parse<BasisContextProjection> { if (!isRecord(v) || !safeRestricted(v.kind)) return fail("unsafe-context", "Context projection is invalid."); const valid = (v.kind === "station-input" && exact(v, ["kind", "inputKind", "attachmentCount"], ["promptExcerpt"]) && safeDisplay(v.inputKind) && (v.promptExcerpt === undefined || safeDisplay(v.promptExcerpt)) && cardinal(v.attachmentCount)) || (v.kind === "thread-result" && exact(v, ["kind", "name", "terminalStatus", "truncatedParts", "omittedParts"], ["textParts"]) && safeDisplay(v.name) && safeDisplay(v.terminalStatus) && (v.textParts === undefined || cardinal(v.textParts)) && cardinal(v.truncatedParts) && cardinal(v.omittedParts)) || (v.kind === "station-output" && exact(v, ["kind", "title", "mediaType", "byteLength", "digest"]) && safeDisplay(v.title) && safeDisplay(v.mediaType) && cardinal(v.byteLength) && safeIdentifier(v.digest)) || (v.kind === "station-live" && exact(v, ["kind", "state", "observedAt"]) && safeDisplay(v.state) && safeTimestamp(v.observedAt)) || (v.kind === "grounded-narrative" && exact(v, ["kind", "statementCount", "sourceCompleteness"]) && cardinal(v.statementCount) && ["complete", "partial", "unknown"].includes(String(v.sourceCompleteness))); return valid ? { ok: true, value: v as BasisContextProjection } : fail("unsafe-context", "Context projection is invalid."); }

function parseRegions(v: unknown): Parse<BasisProjection["regions"]> { const names = ["inputs", "execution", "process", "outcomes", "support", "sources", "live"] as const; if (!exact(v, names)) return fail("invalid-projection", "Regions are invalid."); const output = {} as { [K in keyof BasisProjection["regions"]]: BasisProjection["regions"][K] }; for (const name of names) { const list = v[name]; if (!Array.isArray(list) || list.length > BASIS_MAX_CONTRIBUTIONS) return fail("invalid-projection", "Region cardinality is invalid."); const items: BasisProjection["regions"][typeof name][number][] = []; for (const item of list) { if (!exact(item, ["ref", "role", "context", "gaps"])) return fail("invalid-projection", "Region item is invalid."); const ref = parseContributionRef(item.ref); const context = parseContext(item.context); const gaps = parseGaps(item.gaps); if (!ref.ok) return ref; if (!context.ok) return context; if (!gaps.ok || !validContributionPlacement(ref.value, item.role, context.value.kind) || regionFor(item.role) !== name) return fail("invalid-projection-placement", "Region item is placed outside its published region."); items.push({ ref: ref.value, role: item.role as BasisContribution["role"], context: context.value, gaps: gaps.value }); } output[name] = items; } return { ok: true, value: output }; }
function parseRelationships(v: unknown, assessment: SurfaceAssessmentRead): Parse<BasisProjection["relationships"]> { if (!Array.isArray(v) || v.length > BASIS_MAX_CONTRIBUTIONS) return fail("invalid-projection", "Relationships are invalid."); const output: BasisProjection["relationships"][number][] = []; for (const item of v) { if (!exact(item, ["kind", "from", "to", "source", "gaps"]) || typeof item.from !== "string" || typeof item.to !== "string") return fail("invalid-projection", "Relationship is invalid."); const gaps = parseGaps(item.gaps); if (!gaps.ok) return gaps; if (item.source !== "surface-assessment" || !isSurfaceRelationshipKind(item.kind) || !validSurfaceEndpoints(item.kind, item.from, item.to, assessment)) return fail("relationship-source-mismatch", "Basis relationships must be valid Surface assessment edges."); output.push({ kind: item.kind, from: item.from, to: item.to, source: "surface-assessment", gaps: gaps.value }); } return { ok: true, value: output }; }
function validSurfaceEndpoints(kind: unknown, from: string, to: string, assessment: SurfaceAssessmentRead): boolean { if (assessment.state !== "available" || !assessment.value.found || !assessment.value.claim) return false; const a = assessment.value; const claim = a.claim!.id; return kind === "cites" ? from === claim && a.evidence.cited.some((x) => to === `evidence:${x.id}`) : kind === "supports" ? to === claim && a.evidence.entails.some((x) => x.result !== "failed" && from === `evidence:${x.id}`) : kind === "counterevidence" ? to === claim && a.evidence.counterevidence.some((x) => from === `evidence:${x.id}`) : kind === "derived-from" && from === claim && a.derivation.directInputs.some((x) => to === `claim:${x.claimId}`); }
function parseGaps(v: unknown): Parse<BasisGap[]> { if (!Array.isArray(v) || v.length > BASIS_MAX_CONTRIBUTIONS) return fail("invalid-gaps", "Gaps are invalid."); const gaps: BasisGap[] = []; for (const item of v) { if (!exact(item, ["code", "message"], ["metadata"]) || !safeRestricted(item.code) || !safeDisplay(item.message) || !parseGapMetadata(item.metadata)) return fail("invalid-gaps", "Gap is invalid."); gaps.push(item.metadata === undefined ? { code: item.code, message: item.message } : { code: item.code, message: item.message, metadata: item.metadata as BasisGap["metadata"] }); } return { ok: true, value: gaps }; }
function parseGapMetadata(v: unknown): boolean { return v === undefined || (exact(v, ["source", "weakEdges"]) && v.source === "derivation.weak" && Array.isArray(v.weakEdges) && v.weakEdges.length <= BASIS_MAX_CONTRIBUTIONS && v.weakEdges.every((edge) => exact(edge, ["claimId", "inputClaimId"]) && safeIdentifier(edge.claimId) && safeIdentifier(edge.inputClaimId))); }
function validContributionPlacement(ref: BasisContributionRef, role: unknown, context: BasisContextProjection["kind"]): boolean { return ref.authority === "@kontourai/thread" ? ref.kind === "result" && role === "execution" && context === "thread-result" : ref.authority === "@kontourai/station" && ref.kind === "input" ? role === "input" && context === "station-input" : ref.authority === "@kontourai/station" && ref.kind === "task-output" ? role === "outcome" && context === "station-output" : ref.authority === "@kontourai/station" && ref.kind === "live" ? role === "live" && context === "station-live" : ref.authority === "@kontourai/flow-agents" && ref.kind === "narrative" && role === "execution" && context === "grounded-narrative"; }
function regionFor(role: unknown): keyof BasisProjection["regions"] | null { return role === "input" ? "inputs" : role === "execution" ? "execution" : role === "process" ? "process" : role === "outcome" ? "outcomes" : role === "source" ? "sources" : role === "live" ? "live" : null; }
function isContributionAuthority(v: string): v is BasisContributionRef["authority"] { return v === "@kontourai/thread" || v === "@kontourai/station" || v === "@kontourai/flow-agents"; }
function isSurfaceRelationshipKind(v: unknown): v is "cites" | "supports" | "derived-from" | "counterevidence" { return v === "cites" || v === "supports" || v === "derived-from" || v === "counterevidence"; }
function exact(value: unknown, required: readonly string[], optional: readonly string[] = []): value is R { return hasExactKeys(value, required, optional); }
function isRecord(v: unknown): v is R { return isPlainRecord(v); }
function byteLength(v: string): number | null { if (!isBasisOpaqueRefScalar(v)) return null; return new TextEncoder().encode(v).byteLength; }
function safeDisplay(v: unknown): v is string { return isBasisInertDisplayScalar(v); }
function safeOpaqueId(v: unknown): v is string { return isBasisOpaqueRefScalar(v); }
function safeIdentifier(v: unknown): v is string { return safeRestricted(v); }
function safeRestricted(v: unknown): v is string { return isBasisRestrictedContractScalar(v); }
function safeAuthority(v: unknown): v is string { return isBasisAuthority(v); }
function safeTimestamp(v: unknown): v is string { return safeDisplay(v) && Number.isFinite(Date.parse(v)); }
function cardinal(v: unknown): v is number { return typeof v === "number" && Number.isSafeInteger(v) && v >= 0 && v <= 1_000_000_000; }
function safeSnapshot(input: unknown): Parse<R> {
  const ancestors = new WeakSet<object>(); let nodes = 0; let bytes = 0;
  const account = (text: string, overhead: number) => { const n = byteLength(text); if (n === null || (bytes += n + overhead) > BASIS_MAX_TOTAL_BYTES) throw new Error("oversize"); };
  const visit = (value: unknown, depth: number): unknown => {
    if (++nodes > BASIS_MAX_NODES || depth > BASIS_MAX_DEPTH) throw new Error("limits");
    if (value === null || typeof value === "boolean" || typeof value === "number") return value;
    if (typeof value === "string") { account(value, 2); return value; }
    if (typeof value !== "object" || ancestors.has(value)) throw new Error("hostile");
    ancestors.add(value);
    try {
      if (Array.isArray(value)) {
        const length = Object.getOwnPropertyDescriptor(value, "length");
        if (!length || !("value" in length) || !Number.isSafeInteger(length.value) || length.value > BASIS_MAX_NODES) throw new Error("array-limit");
        const keys = Reflect.ownKeys(value);
        if (keys.length !== length.value + 1 || keys.some((key) => key !== "length" && (typeof key !== "string" || !/^(0|[1-9][0-9]*)$/u.test(key) || Number(key) >= length.value))) throw new Error("array-shape");
        const output: unknown[] = [];
        for (let i = 0; i < length.value; i++) { const descriptor = Object.getOwnPropertyDescriptor(value, String(i)); if (!descriptor || !("value" in descriptor)) throw new Error("accessor"); output.push(visit(descriptor.value, depth + 1)); }
        return output;
      }
      const keys = Reflect.ownKeys(value); if (keys.length > BASIS_MAX_FIELDS) throw new Error("field-limit");
      const output: R = {};
      for (const key of keys) { if (typeof key !== "string") throw new Error("field-limit"); account(key, 3); const descriptor = Object.getOwnPropertyDescriptor(value, key); if (!descriptor || !descriptor.enumerable || !("value" in descriptor)) throw new Error("accessor"); output[key] = visit(descriptor.value, depth + 1); }
      return output;
    } finally { ancestors.delete(value); }
  };
  try { const result = visit(input, 0); return isRecord(result) ? { ok: true, value: result } : fail("invalid-shape", "Basis input must be an object."); } catch { return fail("hostile-input", "Basis input is hostile, cyclic, or exceeds a parser budget."); }
}
function fail(code: string, message: string): { ok: false; gap: BasisGap } { return { ok: false, gap: { code, message } }; }

/** V2 is a parallel closed wire. It delegates all unchanged owner arms to the
 * frozen v1 parser and validates its one additive Fieldwork arm locally. */
export function parseBasisCompositionV2(input: unknown): BasisV2ParseResult {
  const snapshot = safeSnapshot(input); if (!snapshot.ok) return snapshot; const value = snapshot.value;
  if (!exact(value, ["version", "answer", "assessment", "contributions"]) || value.version !== SURFACE_BASIS_V2_VERSION || !Array.isArray(value.contributions)) return fail("invalid-shape", "Basis v2 composition has an invalid shape or version.");
  const fieldwork = value.contributions.filter((read) => isRecord(read) && isRecord(read.owner) && read.owner.authority === "@kontourai/fieldwork");
  for (const read of fieldwork) { const checked = parseFieldworkRead(read, value.answer, value.assessment); if (!checked.ok) return checked; }
  const legacy = { ...value, version: SURFACE_BASIS_VERSION, contributions: value.contributions.map((read) => fieldwork.includes(read as R) ? { owner: { authority: "@kontourai/station" }, state: "not-captured", observedAt: (read as R).observedAt } : read) };
  const parsed = parseBasisComposition(legacy);
  if (!parsed.ok) return parsed;
  return { ok: true, value: { version: SURFACE_BASIS_V2_VERSION, answer: parsed.value.answer, assessment: parsed.value.assessment, contributions: value.contributions as ContributionReadV2[] } };
}

export function parseBasisProjectionV2(input: unknown): BasisV2ProjectionParseResult {
  const snapshot = safeSnapshot(input); if (!snapshot.ok) return snapshot; const value = snapshot.value;
  if (!exact(value, ["version", "answer", "standing", "unresolvedReason", "assessment", "regions", "relationships", "gaps"]) || value.version !== SURFACE_BASIS_V2_VERSION || !isRecord(value.regions)) return fail("invalid-projection", "Basis v2 projection has an invalid shape.");
  const regions = value.regions; const names = ["inputs", "execution", "process", "outcomes", "support", "sources", "live"] as const;
  if (!names.every((name) => Array.isArray(regions[name]))) return fail("invalid-projection", "Basis v2 regions are invalid.");
  const fieldworkItems = (regions.sources as unknown[]).filter((item) => isRecord(item) && isFieldworkRef(item.ref));
  for (const item of fieldworkItems) { const checked = parseFieldworkContribution(item, value.answer, value.assessment, false); if (!checked.ok) return checked; }
  const syntheticRegions: R = { ...regions };
  syntheticRegions.sources = (regions.sources as unknown[]).filter((item) => !fieldworkItems.includes(item as R));
  const legacy = parseBasisProjection({ ...value, version: SURFACE_BASIS_VERSION, regions: syntheticRegions });
  if (!legacy.ok) return legacy;
  return { ok: true, value: { ...legacy.value, version: SURFACE_BASIS_V2_VERSION, regions: regions as BasisProjectionV2["regions"] } };
}

function parseFieldworkRead(read: R, answer: unknown, assessment: unknown): Parse<ContributionReadV2> {
  if (!exact(read, ["owner", "state", "observedAt"], ["value"]) || !exact(read.owner, ["authority"]) || read.owner.authority !== "@kontourai/fieldwork" || !safeTimestamp(read.observedAt)) return fail("invalid-owner-read", "Fieldwork owner read is invalid.");
  if (["restricted", "unsupported-version", "corrupt", "unavailable"].includes(String(read.state))) { if (Object.hasOwn(read, "value")) return fail("invalid-owner-read", "Unavailable Fieldwork reads are descriptor-only."); return { ok: true, value: read as ContributionReadV2 }; }
  if (read.state !== "available" || !Array.isArray(read.value)) return fail("invalid-owner-read", "Fieldwork owner read is invalid.");
  for (const value of read.value) { const parsed = parseFieldworkContribution(value, answer, assessment, true); if (!parsed.ok) return parsed; }
  return { ok: true, value: read as ContributionReadV2 };
}
function isFieldworkRef(value: unknown): value is R { return isRecord(value) && value.authority === "@kontourai/fieldwork"; }
function parseFieldworkContribution(value: unknown, answer: unknown, assessment: unknown, requireAnswer: boolean): Parse<unknown> {
  if (!isRecord(value) || !exact(value, requireAnswer ? ["ref", "answer", "role", "context"] : ["ref", "role", "context", "gaps"], requireAnswer ? ["gaps"] : []) || !isFieldworkRef(value.ref) || !exact(value.ref, ["authority", "schemaVersion", "kind", "exactRef", "evidenceId"]) || value.ref.schemaVersion !== "fieldwork.kontourai.io/v1" || value.ref.kind !== "reviewed-web-source" || typeof value.ref.exactRef !== "string" || !/^fieldwork-reviewed-source:v1:[a-f0-9]{64}$/.test(value.ref.exactRef) || !safeIdentifier(value.ref.evidenceId)) return fail("invalid-contribution-ref", "Fieldwork contribution requires the published exact ref.");
  if (requireAnswer) { const parsedAnswer = parseThreadAnswerRef(value.answer); if (!parsedAnswer.ok || !sameAnswer(parsedAnswer.value, answer)) return fail("answer-owner-spoof", "Contribution must bind the exact answer observation."); }
  if (value.role !== "source") return fail("invalid-contribution-placement", "Fieldwork reviewed source belongs in Sources.");
  const context = parseReviewedSourceContext(value.context); if (!context.ok) return context;
  if (context.value.sourceEvidenceId !== value.ref.evidenceId || context.value.assessmentRevision < 1) return fail("reviewed-source-binding-mismatch", "Reviewed source binding is incoherent.");
  const assessmentParsed = parseAssessmentRead(assessment); if (!assessmentParsed.ok) return assessmentParsed;
  if (assessmentParsed.value.state === "available") {
    const a = assessmentParsed.value.value;
    if (!a.found || !a.claim || a.claim.id !== context.value.answerClaimId || a.ref.claimId !== context.value.answerClaimId || a.evidence.cited.filter((item) => item.id === context.value.answerCitationEvidenceId).length !== 1 || a.derivation.directInputs.filter((item) => item.claimId === context.value.sourceClaimId).length !== 1) return fail("reviewed-source-association-mismatch", "Reviewed source does not match the Surface assessment.");
  }
  return { ok: true, value };
}
function parseReviewedSourceContext(value: unknown): Parse<Extract<BasisContextProjectionV2, { kind: "reviewed-source" }>> {
  if (!exact(value, ["kind", "sourceClaimId", "sourceEvidenceId", "answerClaimId", "answerCitationEvidenceId", "assessmentRevision", "review", "reviewedAt", "currentness", "checkedAt", "expectedCapture", "observedCapture"]) || value.kind !== "reviewed-source" || !safeIdentifier(value.sourceClaimId) || !safeIdentifier(value.sourceEvidenceId) || !safeIdentifier(value.answerClaimId) || !safeIdentifier(value.answerCitationEvidenceId) || !Number.isSafeInteger(value.assessmentRevision) || (value.assessmentRevision as number) < 1 || !["accepted", "not-accepted", "not-captured"].includes(String(value.review)) || !(value.reviewedAt === null || safeTimestamp(value.reviewedAt)) || !["current", "drifted", "unknown"].includes(String(value.currentness)) || !safeTimestamp(value.checkedAt) || !capture(value.expectedCapture) || !capture(value.observedCapture)) return fail("unsafe-context", "Reviewed source context is invalid.");
  const noCaptures = value.expectedCapture === null && value.observedCapture === null;
  const bothCaptures = value.expectedCapture !== null && value.observedCapture !== null;
  if ((value.currentness === "unknown" && !noCaptures) || (value.currentness !== "unknown" && !bothCaptures)) return fail("unsafe-context", "Reviewed source capture facts are incoherent.");
  const expectedCapture = value.expectedCapture as { contentDigest: string } | null; const observedCapture = value.observedCapture as { contentDigest: string } | null;
  if (value.currentness === "current" && bothCaptures && expectedCapture!.contentDigest !== observedCapture!.contentDigest) return fail("unsafe-context", "Current reviewed source captures must agree.");
  if (value.currentness === "drifted" && bothCaptures && expectedCapture!.contentDigest === observedCapture!.contentDigest) return fail("unsafe-context", "Drifted reviewed source captures must differ.");
  return { ok: true, value: value as unknown as Extract<BasisContextProjectionV2, { kind: "reviewed-source" }> };
}
function capture(value: unknown): boolean { return value === null || (exact(value, ["capturedAt", "contentDigest"]) && safeTimestamp(value.capturedAt) && typeof value.contentDigest === "string" && /^[a-f0-9]{64}$/.test(value.contentDigest)); }
function sameAnswer(left: ThreadAnswerRef, read: unknown): boolean { const parsed = parseAnswerRead(read); return parsed.ok && parsed.value.state === "available" && parsed.value.value.ref.threadId === left.threadId && parsed.value.value.ref.messageId === left.messageId; }
