// Generated by scripts/build-console-assets.mjs from src/console/client/parts/.
// Do not edit directly; edit the ordered part files instead.
// Build order: state.js, format.js, analysis.js, dashboard.js, detail.js, routing-help.js, authoring.js, runs.js, live.js
